
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/hoostelstudios/HystelMC/issues" #optional

[[mods]] #mandatory

modId="hm" #mandatory

version="1.2.1" #mandatory

displayName="HystelMC" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/hystel-mc" #optional

logoFile="logo.png" #optional

credits="All rights go to Hystel Studios" #optional

authors="Hystel Studios" #optional

description='''
A description!
'''

[[dependencies.hystelmc]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.hystelmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
