package com.victor.HystelMC.setup;

public enum DICKEL {

    START, A_NEUM, HIPPOH, RIPPAD, DIIIICA, hm1144, H1920, ASAP, TATGAP, CFP, IOCF, ENDERIO, OBFUSCATE, DISEL, LISEK, MSLAVA, SETUP, START_PROB;
}
